// sync-version.mjs — copy the crate's version into a committed TS constant so the
// site's version badge always matches what's actually released.
//
// Vercel uploads only apps/web, so the site cannot read ../../crates/.../Cargo.toml
// at build time on the server. Instead we bake the version into app/version.ts and
// commit it. This script refreshes that file from the crate whenever the crate is
// reachable (local builds / deploys); on Vercel the crate is absent, so it no-ops
// and the committed value ships. Wired as a `prebuild` step and run before deploy.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const cargo = join(here, "..", "..", "..", "crates", "muxpilot", "Cargo.toml");
const out = join(here, "..", "app", "version.ts");

if (!existsSync(cargo)) {
  // On Vercel (only apps/web is uploaded) the crate isn't present — keep the
  // committed version.ts as-is.
  console.log("sync-version: crate Cargo.toml not found; keeping committed version");
  process.exit(0);
}

const toml = readFileSync(cargo, "utf8");
const match = toml.match(/^version\s*=\s*"([^"]+)"/m);
if (!match) {
  console.error("sync-version: could not parse version from Cargo.toml");
  process.exit(1);
}
const version = match[1];
const banner =
  "// Generated by scripts/sync-version.mjs from crates/muxpilot/Cargo.toml.\n" +
  "// Do not edit by hand; run `node scripts/sync-version.mjs` (or `pnpm build`).\n";
writeFileSync(out, `${banner}export const MUXPILOT_VERSION = "${version}";\n`);
console.log(`sync-version: wrote app/version.ts (v${version})`);
